name: Publish

# Run this workflow every time a new release is created
on:
  release:
    types: [released]

# A workflow run is made up of one or more sequential or parallel jobs
jobs:
  # This workflow contains a single job called "publish"
  publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps are a sequence of tasks that will be executed as part of the job
    steps:
      # Check out repository under $GITHUB_WORKSPACE, so the job can access it
      - name: Checkout code
        uses: actions/checkout@v4

      # Analyzer runs on Node.js — we need to set this up first
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"

      # Clean install dependencies
      - name: Install
        run: npm ci

      # Buld the project
      - name: Build
        run: npm run build

      # Publish to NPM
      - name: Publish to registry
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
